# Generated by Django 3.1.5 on 2021-02-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0004_remove_groupstorage_group_max_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='project',
        ),
        migrations.AddField(
            model_name='paper',
            name='project',
            field=models.ManyToManyField(to='papermanager.Project'),
        ),
    ]
