# Generated by Django 3.1.5 on 2021-02-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0007_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstorage',
            name='user_init_storage',
            field=models.IntegerField(default=0, verbose_name='Default User Storage (MiB)'),
        ),
        migrations.AlterField(
            model_name='userstorage',
            name='specific_storage',
            field=models.IntegerField(default=0, verbose_name='Purchased Storage (MiB)'),
        ),
        migrations.DeleteModel(
            name='ShareLink',
        ),
    ]
