# Generated by Django 3.1.5 on 2021-03-03 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papermanager', '0008_auto_20210216_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Label',
        ),
    ]
