# Generated by Django 3.1.5 on 2021-03-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0009_auto_20210303_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='project',
            new_name='labels',
        ),
    ]
