# Generated by Django 3.1.5 on 2021-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='group',
        ),
        migrations.AddField(
            model_name='register',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
