# Generated by Django 3.1.5 on 2021-03-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papershare', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
