# Generated by Django 3.1.5 on 2021-03-16 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papermanager', '0011_auto_20210314_1612'),
        ('papershare', '0002_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('papers', models.ManyToManyField(blank=True, to='papermanager.Paper')),
                ('to_user', models.ManyToManyField(blank=True, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
